<?php

namespace Compufix\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function contar() {
        return $this->getEntityManager()
                        ->createQuery('SELECT (a) FROM CompufixUserBundle:User')
                        ->getResult();
    }

}
